VIA_ENABLE = yes
VIAL_ENABLE = yes

VIALRGB_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
SPLIT_POINTING_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
MOUSEKEY_ENABLE = yes

SPLIT_ENCODER_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
