units:
  outlinePadding: 1

  plateThickness: 1.6
  pcbThickness: 1.6

  keyCutoutDimentions: 13.95

  # Case
  baseHeight: 3
  screwRadius: 1.1 # M2 + 0.2mm buffer
  screwHoleRadius: 1.55
  screwHoleWallThickness: 2
  screwHeadRadius: 2.1 # 4mm + 0.2mm buffer
  fromPlateToTop: 5

  baseWallHeight: baseHeight + pcbThickness
  topWallHeight: 2.2
  wallThickness: 1.6

points:
  zones:
    matrix:
      anchor:
        shift: [40, -180] # Move into KiCAD position
      columns:
        outer.key.column_net: "GP29"
        outer.rows.bottom.skip: true

        pinky.key.column_net: "GP28"
        pinky.key.stagger: 0.4U

        ring.key.column_net: "GP27"
        ring.key.stagger: 0.6U

        middle.key.column_net: "GP26"
        middle.key.stagger: 0.2U

        index.key.column_net: "GP15"
        index.key.stagger: -0.25U

        inner.key.column_net: "GP14"
        inner.key.stagger: -0.2U
      rows:
        bottom.row_net: "GP12"
        home.row_net: "GP11"
        top.row_net: "GP10"
        num.row_net: "GP9"
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [0U, -1.3U]
      columns:
        inner:
          key.name: matrix_thumb_inner
          key.column_net: "GP26"
          key.origin: [-0.5U, -0.5U]
        center:
          key.name: matrix_thumb_center
          key.column_net: "GP15"
          key.splay: -15
          key.origin: [-0.5U, -0.5U]
        outer:
          key.name: matrix_thumb_outer
          key.column_net: "GP14"
          key.splay: -10
          key.origin: [-0.5U, -0.5U]
      rows:
        only:
          row_net: "GP13"
    screw_1:
      anchor:
        - ref: matrix_inner_bottom
          shift: [13, -9.5]
    screw_2:
      anchor:
        - ref: matrix_inner_num
          shift: [13, 21.5]
    screw_3:
      anchor:
        - ref: matrix_inner_num
          shift: [-5U-13, 21.5]
    screw_4:
      anchor:
        - ref: matrix_outer_home
          shift: [-13, -24]
    screw_5:
      anchor:
        - ref: matrix_middle_bottom
          shift: [0, -24]
    screw_thumb:
      anchor:
        - ref: matrix_thumb_outer
          shift: [8.5, 8.5]
    knob:
      anchor:
        - ref: matrix_pinky_num
          shift: [-0U, 1U]
      columns.only.key.column_net: "GP28"
      rows.only.row_net: "GP8"
  mirror:
    ref: matrix_pinky_home
    distance: 270
outlines:
  _keysCutout:
    - what: rectangle
      size: [keyCutoutDimentions, keyCutoutDimentions]
      fillet: 0.1
  _knobCutout:
    - what: rectangle
      size: [14, 15]
      fillet: 0.1

  _rightSubstitution:
    - what: rectangle
      size: 10U
      where:
        ref: mirror_matrix_middle_home

  _leftSubstitution:
    - what: rectangle
      size: 10U
      where:
        ref: matrix_middle_home

  _bottomKeyCutout:
    - what: rectangle
      size: [16.5, 15.5]
      adjust.shift: [-1.5, -1]
      fillet: 4
  
  _bottomKnobCutout:
    - what: rectangle
      size: [7, 1.5]
      adjust.shift: [0,7.5]
      fillet: 0.5
    - what: rectangle
      size: [7, 1.5]
      adjust.shift: [0,-7]
      fillet: 0.5
    - what: rectangle
      size: [2.3, 3]
      adjust.shift: [5.6,0]
      fillet: 0.5
    - what: rectangle
      size: [2.3, 3]
      adjust.shift: [-5.6,0]
      fillet: 0.5

  _MCUPCBCutout:
    - what: rectangle
      size: [13, 20.5]
      where: /matrix_outer_num/
      adjust.shift: [-1, 27.24+3]
  _MCUTopCutout:
    - what: rectangle
      size: [13, 5]
      where: /matrix_outer_num/
      adjust.shift: [-1, 27.24-4.35]
      operation: stack
    - what: rectangle
      size: [9.5, 12]
      where: /matrix_outer_num/
      adjust.shift: [-1, 27.24+10.75]
      expand: 0.1
      operation: stack
  _MCUBottomCutout:
    - what: rectangle
      size: [18.5, 24]
      where: /matrix_outer_num/
      adjust.shift: [-1, 27.24]
  _MCUUSBCutout:
    - what: rectangle
      size: [9.5, 20]
      where: /matrix_outer_num/
      adjust.shift: [-1, 27.24+10]
  _USBSerialCutout:
    - what: rectangle
      size: [10, 8.5]
      where: /matrix_inner_num/
      adjust: &usbPosition
        shift: [0, 22.5]
        rotate: 180
    - what: rectangle
      where: /matrix_inner_num/
      size: [10, 10]
      adjust: 
        shift: [0, 30]

  _expansionCutout:
    - what: rectangle
      size: [2.54, 23]
      where: /matrix_inner_home/
      adjust.shift: [13,-9]
      expand: 0.5

  _expansionCutoutTopCase:
    - what: rectangle
      size: [2.54+10, 23]
      where: /matrix_inner_home/
      adjust.shift: [13+5,-9]
      expand: 0.5

  _PCBCutouts:
    - what: outline
      name: _MCUPCBCutout
    
  _bottomCutout:
    - what: outline
      name: _bottomKeyCutout
      where: /matrix/
    - what: outline
      name: _bottomKnobCutout
      where: /knob/
    - what: outline
      name: _expansionCutout
  
  _knobRotaryCutout:
    - what: circle
      radius: 10
      where: /knob/
  _knobStickCutout:
    - what: circle
      radius: 4
      where: /knob/
  _knobBaseCutout:
    - what: outline
      name: _knobCutout
      where: /knob/
  _knobCutoutExtraAtKeys:
    - what: rectangle
      size: [10, 10]
      where: /knob/
      adjust.shift: [5,-5]
  _screwRecess:
    - what: circle
      radius: screwHeadRadius
      where: /screw/
    - what: circle
      radius: screwHeadRadius+1
      where: /screw_thumb/
      operation: subtract

  _screwRecessPlate:
    - what: circle
      radius: screwHeadRadius
      where: /screw_thumb/
  
  _holesBottom:
    - what: circle
      radius: screwRadius
      where: /screw/
    - what: circle
      radius: screwRadius+1
      where: /screw_thumb/
      operation: subtract
    - what: circle
      radius: screwHoleRadius
      where: /screw_thumb/
  
  _holesTop:
    - what: circle
      radius: screwHoleRadius
      where: /screw/
    - what: circle
      radius: screwHoleRadius +1
      operation: subtract
      where: /screw_thumb/
    - what: circle
      radius: screwRadius
      where: /screw_thumb/

  _standOff:
    - what: circle
      radius: screwHoleRadius
      expand: screwHoleWallThickness
      where: /screw_thumb/
    - what: circle
      radius: screwHoleRadius
      operation: subtract
      where: /screw_thumb/

  # Main outline
  _outline:
    - what: polygon
      points:
        - ref: matrix_pinky_bottom
          shift: [-1.8U, -0.8U]
        - ref: matrix_middle_num
          shift: [-3.8U, 0.8U]
        - ref: matrix_middle_num
          shift: [2.8U, 0.8U]
        - ref: matrix_middle_num
          shift: [2.8U, -4.5U]
        - ref: matrix_thumb_outer
          shift: [-1U, 0.5U]
        - ref: matrix_thumb_outer
          shift: [0.5U, 0.5U]
        - ref: matrix_thumb_outer
          shift: [0.5U, -0.5U]
        - ref: matrix_thumb_inner
          shift: [-0.5U, 0.5U]
        - ref: matrix_pinky_bottom
          shift: [2.5U, -0.8U]
    - what: polygon
      points:
        - ref: mirror_matrix_pinky_bottom
          shift: [-1.8U, -0.8U]
        - ref: mirror_matrix_middle_num
          shift: [-3.8U, 0.8U]
        - ref: mirror_matrix_middle_num
          shift: [2.8U, 0.8U]
        - ref: mirror_matrix_middle_num
          shift: [2.8U, -4.5U]
        - ref: mirror_matrix_thumb_outer
          shift: [-1U, 0.5U]
        - ref: mirror_matrix_thumb_outer
          shift: [0.5U, 0.5U]
        - ref: mirror_matrix_thumb_outer
          shift: [0.5U, -0.5U]
        - ref: mirror_matrix_thumb_inner
          shift: [-0.5U, 0.5U]
        - ref: mirror_matrix_pinky_bottom
          shift: [2.5U, -0.8U]
      fillet: 0.5
    # Around keys
    - what: rectangle
      where: /matrix/
      size: [U, U]
      expand: outlinePadding
      fillet: 0.5

  _outlinePCB:
    - what: outline
      name: _outline
    - what: outline
      name: _PCBCutouts
      operation: subtract
      fillet: 0.5
    - what: outline
      name: _rightSubstitution
      operation: subtract


  # Case Outlines
  _caseOutline:
    - what: outline
      name: _outline
      expand: 0.5

  _caseWalls:
    - what: outline
      name: _caseOutline
      expand: wallThickness
    - what: outline
      name: _caseOutline
      operation: subtract

  _casePlate:
    - what: outline
      name: _caseOutline
    - what: outline
      name: _keysCutout
      operation: subtract
      where: /matrix/

  _keySupportPlate:
    - what: outline
      name: _casePlate
    - what: rectangle
      size: [keyCutoutDimentions+1, keyCutoutDimentions+1]
      where: /matrix/
      operation: subtract

  _caseTop:
    - what: outline
      name: _caseOutline
      expand: wallThickness
    - what: outline
      name: _caseWalls
    - what: rectangle
      size: [20, 20]
      where: /matrix/
      operation: subtract
    - what: polygon
      points:
        - ref: matrix_thumb_outer
          shift: [0, 11]
        - ref: matrix_thumb_outer
          shift: [-25, 11]
        - ref: matrix_index_home
          shift: [-10, 0]
        - ref: matrix_index_home
          shift: [-10, -40]
        - ref: matrix_thumb_inner
          shift: [10, -10]
        - ref: matrix_thumb_outer
      operation: subtract
    - what: polygon
      points:
        - ref: matrix_inner_bottom
          shift: [10, 0]
        - ref: matrix_inner_bottom
          shift: [10, -20]
        - ref: matrix_inner_bottom
          shift: [-10, -20]
      operation: subtract
    - what: polygon
      points:
        - ref: matrix_thumb_inner
          shift: [-20, -4.05]
        - ref: matrix_thumb_inner
          shift: [0, -4.05]
        - ref: matrix_thumb_inner
          shift: [0, 0]
        - ref: matrix_inner_bottom
          shift: [18.45, -30]
        - ref: matrix_inner_bottom
          shift: [18.45, -5]
        - ref: matrix_thumb_outer
          shift: [20, 20]
        - ref: matrix_thumb_outer
          shift: [20, -20]
        - ref: matrix_thumb_inner
          shift: [-20, -20]
      operation: subtract
    - what: polygon
      points:
        - ref: mirror_matrix_thumb_outer
          shift: [0, 11]
        - ref: mirror_matrix_thumb_outer
          shift: [-25, 11]
        - ref: mirror_matrix_index_home
          shift: [-10, 0]
        - ref: mirror_matrix_index_home
          shift: [-10, -40]
        - ref: mirror_matrix_thumb_inner
          shift: [10, -10]
        - ref: mirror_matrix_thumb_outer
      operation: subtract
    - what: polygon
      points:
        - ref: mirror_matrix_inner_bottom
          shift: [10, 0]
        - ref: mirror_matrix_inner_bottom
          shift: [10, -20]
        - ref: mirror_matrix_inner_bottom
          shift: [-10, -20]
      operation: subtract
    - what: polygon
      points:
        - ref: mirror_matrix_thumb_inner
          shift: [-20, -4.05]
        - ref: mirror_matrix_thumb_inner
          shift: [0, -4.05]
        - ref: mirror_matrix_thumb_inner
          shift: [0, 0]
        - ref: mirror_matrix_inner_bottom
          shift: [18.45, -30]
        - ref: mirror_matrix_inner_bottom
          shift: [18.45, -5]
        - ref: mirror_matrix_thumb_outer
          shift: [20, 20]
        - ref: mirror_matrix_thumb_outer
          shift: [20, -20]
        - ref: mirror_matrix_thumb_inner
          shift: [-20, -20]
      operation: subtract
      fillet: 0.75

  _outlineBottom:
    - what: outline
      name: _caseOutline
    - what: outline
      name: _bottomCutout
      operation: subtract

  representation:
    - what: outline
      name: _caseWalls
    - what: outline
      name: _caseTop
    - what: rectangle
      size: [18, 18]
      where: /matrix/
      operation: stack
    - what: circle
      radius: 9
      where: /^knob/
      operation: stack
    - what: circle
      radius: 10
      where: /^knob/
      operation: stack

cases:
  _knobNegative:
    - what: outline
      name: _knobBaseCutout
      extrude: 6.5
    - what: outline
      name: _knobStickCutout
      extrude: 15
    - what: outline
      name: _knobRotaryCutout
      extrude: 20
      shift: [0, 0, 6]
    - what: outline
      name: _knobCutoutExtraAtKeys
      extrude: 20
      shift: [0, 0, 6]

  _bottom:
    - what: outline
      name: _outlineBottom
      extrude: baseHeight+1
    - what: outline
      name: _caseWalls
      extrude: baseWallHeight+1
    - what: outline
      name: _caseOutline
      extrude: 1
    - what: outline
      name: _screwRecess
      extrude: 0.6
      operation: subtract
    - what: outline
      name: _standOff
      extrude: baseHeight+1
    - what: outline
      name: _holesBottom
      extrude: 20
      operation: subtract
    - what: outline
      name: _screwRecessPlate # Cover up the thumb standoff
      extrude: 1

  bottomLeft:
    - what: case
      name: _bottom

    - what: outline
      name: _MCUBottomCutout
      extrude: 3
      operation: subtract
      shift: [0,0,baseHeight+1-3]

    - what: outline
      name: _rightSubstitution
      extrude: 100
      shift: [0, 0, -50]
      operation: subtract

  bottomRight:
    - what: case
      name: _bottom

    - what: outline
      name: _MCUTopCutout
      extrude: 3.5
      operation: subtract
      shift: [0,0,baseHeight+pcbThickness+1-3.5]

    - what: outline
      name: _leftSubstitution
      extrude: 100
      shift: [0, 0, -50]
      operation: subtract

  _top: # plane is pcb top
    - what: outline
      name: _caseWalls
      extrude: topWallHeight
    - what: outline
      name: _keySupportPlate
      extrude: topWallHeight
    - what: outline
      name: _casePlate
      extrude: plateThickness
      shift: [0, 0, 2.2-plateThickness]
    - what: outline
      name: _screwRecessPlate
      extrude: 0.6
      shift: [0, 0, 2.2-0.6]
      operation: subtract
    - what: outline
      name: _caseTop
      extrude: 5+2.2
    - what: outline
      name: _holesTop
      extrude: 4.5
      operation: subtract
      shift: [0, 0, 0]
    - what: outline
      name: _USBSerialCutout
      extrude: 3
      operation: subtract

  topLeft:
    - what: case
      name: _top

    - what: outline
      name: _MCUTopCutout
      extrude: 3.5
      operation: subtract

    - what: case
      name: _knobNegative
      operation: subtract

    - what: outline
      name: _rightSubstitution
      extrude: 100
      shift: [0, 0, -50]
      operation: subtract

  topRight:
    - what: case
      name: _top

    - what: outline
      name: _MCUBottomCutout
      extrude: 3
      operation: subtract

    - what: outline
      name: _expansionCutoutTopCase
      extrude: 4.5
      operation: subtract

    - what: outline
      name: _leftSubstitution
      extrude: 100
      shift: [0, 0, -50]
      operation: subtract

pcbs:
  pcb:
    template: kicad8
    outlines:
      - outline: _outlinePCB
    footprints:
      MCU: 
        what: rp2040zero
        where: matrix_outer_num
        params:
          flip: false
          side: B
          GP0: SERIAL_DATA
          GP1: LED_IN
        adjust.shift: [-11.14, 14.68]
      usb_serial:
        what: usc_c_6pin_receptacle
        where: matrix_inner_num
        params:
          GND: GND
          VCC: P5V
          CC1: SERIAL_DATA
          CC2: SERIAL_DATA
        adjust: *usbPosition
      socketsChocv2: 
        what: ceoloide/switch_choc_v1_v2
        where: /^matrix/
        params:
          reversible: true
          choc_v1_support: true
          include_stabilizer_pad: false
          include_keycap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust.rotate: 180
      knob:
        what: ceoloide/rotary_encoder_ec11_ec12
        where: /^knob/
        params:
          reversible: true
          include_plate_hole_marking: true
          S1: "{{column_net}}"
          S2: "{{row_net}}"
          A: GP2 #A Pin in schematics
          B: GND #C Pin
          C: GP3 #B Pin 
        adjust.rotate: 180
      diode:
        what: ceoloide/diode_tht_sod123
        where: /^matrix/
        params:
          reversible: true
          include_tht: false
          include_traces_vias: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust.shift: [-8.3, 1.5]
        adjust.rotate: 270
      mountingHoles: &holes
        what: ceoloide/mounting_hole_npth
        where: /^screw/
      expansion: 
        what: pin_header_6pin
        where: matrix_inner_home
        params:
          P1: P3V3
          P2: GND
          P3: GP4
          P4: GP5
          P5: GP6
          P6: GP7
        adjust.shift: [13,-9]
      rowRoute: 
        what: ceoloide/utility_router
        where: /^matrix/
        params:
          width: 0.2
          route: "b(-8.3,3.8)(-8.3,0.2)|(-8.3,-3.2)(-8.3,-8.9)v|(-8.3, -8.9)(8.5, -8.9)"
      colRoute: 
        what: ceoloide/utility_router
        where: /^matrix/
        params:
          width: 0.2
          route: "b(4.3,6)(8.6,6)"
      ledFirst: 
        what: ceoloide/led_sk6812mini-e
        where: matrix_outer_num
        params:
          reversible: true
          via_size: 0.6
          via_drill: 0.3
          gnd_trace_width: 0.4
          vcc_trace_width: 0.4
          P1: P5V
          P2: LED_NET
          P3: GND
          P4: LED_IN
        adjust.shift: [0, 5]
      leds: 
        what: ceoloide/led_sk6812mini-e
        where: /^matrix_(inner|index|middle|ring|pinky|outer_top|outer_home|thumb)/
        params:
          reversible: true
          via_size: 0.6
          via_drill: 0.3
          gnd_trace_width: 0.4
          vcc_trace_width: 0.4
          P1: P5V
          P2: LED_NET
          P3: GND
          P4: LED_NET
        adjust.shift: [0, 5]
      gndRoute: 
        what: ceoloide/utility_router
        where: /^matrix/
        params:
          width: 0.4
          route: "b(-4.06, -4.3)(-4.06, -8.1)v|(-8.5, -8.1)(8.5, -8.1)"
      5vRoute: 
        what: ceoloide/utility_router
        where: /^matrix/
        params:
          width: 0.4
          route: "b(2.7,-4.4)(6.2,-4.4)(6.2,-7.3)v|(-8.5,-7.3)(8.5,-7.3)"
      outRoute: 
        what: ceoloide/utility_router
        where: /^matrix/
        params:
          width: 0.25
          route: "f(5,-5.7)(8.5,-5.7)"
      inRoute: 
        what: ceoloide/utility_router
        where: /^matrix/
        params:
          width: 0.25
          route: "f(-4.94,-5.7)(-8.5,-5.7)"
      orientationLeftText: 
        what: ceoloide/utility_text
        where: matrix_index_num
        params:
          text: "(left) ⌨"
          height: 2
          width: 2
        adjust:
          shift: [0, 12]
      orientationRightText: 
        what: ceoloide/utility_text
        where: matrix_index_num
        params:
          side: B
          mirrored: true
          text: "(right) ⌨"
          height: 2
          width: 2
        adjust:
          shift: [0, 12]
      byText: 
        what: ceoloide/utility_text
        where: matrix_index_num
        params:
          reversible: true
          text: "NWSplit Rev. V \\nby NWSteenberg"
        adjust:
          shift: [0, 17]
