#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_PIN_SWAP

#define WS2812_DI_PIN GP2
#define WS2812_DO_PIN GP3
#define RGB_MATRIX_LED_COUNT 54   // total LEDs across both halves
#define RGB_MATRIX_SPLIT
#define SPLIT_TRANSPORT_MIRROR
#define RGB_MATRIX_SPLIT_LEFT 27
#define RGB_MATRIX_SPLIT_RIGHT 27
