#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define SERIAL_USART_DRIVER SD1
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP0

#define WS2812_PIO_IRQ_PRIORITY 0
#define RGB_MATRIX_SPLIT_SEND_DELAY 5
#define RGB_MATRIX_MAXIMUM_SPEED 100
#define RGB_MATRIX_KEYPRESSES
#define RGBLIGHT_SLEEP
#define RGBLIGHT_SPLIT
